// DIU CSE Routine - Frontend JavaScript
// This file only reads the local routine.json file generated by GitHub Actions

const ROUTINE_DATA_PATH = './data/routine.json';
const STORAGE_KEY = 'diu_cse_section';

// DOM Elements
const sectionInput = document.getElementById('sectionInput');
const showRoutineBtn = document.getElementById('showRoutineBtn');
const clearSectionBtn = document.getElementById('clearSectionBtn');
const routineContainer = document.getElementById('routineContainer');
const statusMessage = document.getElementById('statusMessage');
const statusIndicator = document.getElementById('statusIndicator');
const lastUpdated = document.getElementById('lastUpdated');

// State
let currentRoutineData = null;
let selectedSection = null;

// Initialize
document.addEventListener('DOMContentLoaded', () => {
    // Load saved section
    const savedSection = localStorage.getItem(STORAGE_KEY);
    if (savedSection) {
        sectionInput.value = savedSection;
    }
    
    // Load routine data
    loadRoutineData();
    
    // Event Listeners
    showRoutineBtn.addEventListener('click', handleShowRoutine);
    clearSectionBtn.addEventListener('click', handleClearSection);
    sectionInput.addEventListener('keypress', (e) => {
        if (e.key === 'Enter') {
            handleShowRoutine();
        }
    });
});

async function loadRoutineData() {
    try {
        showStatus('Loading routine data...', 'info');
        setStatusIndicator('loading', 'Loading...');
        
        // Add cache-busting timestamp
        const url = `${ROUTINE_DATA_PATH}?t=${Date.now()}`;
        const response = await fetch(url);
        
        if (!response.ok) {
            throw new Error(`HTTP ${response.status}: ${response.statusText}`);
        }
        
        const data = await response.json();
        currentRoutineData = data;
        
        // Update last updated time
        if (data.updated_at) {
            const date = new Date(data.updated_at);
            lastUpdated.textContent = `Last updated: ${date.toLocaleString()}`;
        }
        
        setStatusIndicator('success', '● Ready');
        hideStatus();
        
        // Auto-show saved section
        const savedSection = localStorage.getItem(STORAGE_KEY);
        if (savedSection && data.sections) {
            const normalized = normalizeSection(savedSection);
            const matchedSection = findMatchingSection(data.sections, normalized);
            if (matchedSection) {
                selectedSection = matchedSection;
                displayRoutine(data.sections[matchedSection], matchedSection);
                showStatus(`Showing routine for ${matchedSection}`, 'success');
            } else {
                showRoutineContainer(createNoRoutineMessage('No routine found for your saved section.'));
            }
        } else if (data.sections && Object.keys(data.sections).length > 0) {
            // Show first section if no saved section
            const firstSection = Object.keys(data.sections)[0];
            selectedSection = firstSection;
            displayRoutine(data.sections[firstSection], firstSection);
        }
        
    } catch (error) {
        console.error('Failed to load routine data:', error);
        setStatusIndicator('error', '● Error');
        showStatus('Routine data is currently unavailable. Please try again later.', 'error');
        showRoutineContainer(createErrorMessage('Routine data is currently unavailable.', 
            'The routine data could not be loaded. This might be because the GitHub Action hasn\'t run yet or there was an error scraping the data.'));
    }
}

function handleShowRoutine() {
    const section = sectionInput.value.trim();
    
    if (!section) {
        showStatus('Please enter a section.', 'error');
        return;
    }
    
    if (!currentRoutineData || !currentRoutineData.sections) {
        showStatus('Routine data is not loaded yet. Please try again.', 'error');
        return;
    }
    
    const normalized = normalizeSection(section);
    const matchedSection = findMatchingSection(currentRoutineData.sections, normalized);
    
    if (matchedSection) {
        selectedSection = matchedSection;
        localStorage.setItem(STORAGE_KEY, section);
        displayRoutine(currentRoutineData.sections[matchedSection], matchedSection);
        showStatus(`Showing routine for ${matchedSection}`, 'success');
    } else {
        showStatus(`No routine found for section "${section}". Please check your section name.`, 'error');
        showRoutineContainer(createNoRoutineMessage(`No routine found for section "${section}"`));
    }
}

function handleClearSection() {
    localStorage.removeItem(STORAGE_KEY);
    sectionInput.value = '';
    selectedSection = null;
    showStatus('Saved section cleared.', 'info');
    
    // Show first section if available
    if (currentRoutineData && currentRoutineData.sections) {
        const sections = Object.keys(currentRoutineData.sections);
        if (sections.length > 0) {
            const firstSection = sections[0];
            displayRoutine(currentRoutineData.sections[firstSection], firstSection);
        }
    }
}

function displayRoutine(routineData, sectionName) {
    if (!routineData || routineData.length === 0) {
        showRoutineContainer(createNoRoutineMessage(`No classes found for section "${sectionName}"`));
        return;
    }
    
    // Sort by day order
    const dayOrder = ['Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];
    const sorted = [...routineData].sort((a, b) => {
        const dayA = dayOrder.indexOf(a.day);
        const dayB = dayOrder.indexOf(b.day);
        return dayA - dayB;
    });
    
    let html = `<h3>Routine for ${sectionName}</h3>`;
    html += `<div class="routine-table-wrapper"><table class="routine-table">`;
    html += `<thead><tr>
        <th>Day</th>
        <th>Time</th>
        <th>Course</th>
        <th>Teacher</th>
        <th>Room</th>
        <th>Type</th>
    </tr></thead><tbody>`;
    
    sorted.forEach(classItem => {
        const typeClass = classItem.type === 'Lab' ? 'type-lab' : 'type-theory';
        html += `<tr>
            <td class="day-cell">${escapeHtml(classItem.day)}</td>
            <td>${escapeHtml(classItem.time)}</td>
            <td><strong>${escapeHtml(classItem.course)}</strong></td>
            <td>${escapeHtml(classItem.teacher)}</td>
            <td>${escapeHtml(classItem.room)}</td>
            <td><span class="type-tag ${typeClass}">${escapeHtml(classItem.type)}</span></td>
        </tr>`;
    });
    
    html += `</tbody></table></div>`;
    html += `<div style="margin-top: 10px; font-size: 0.85rem; color: #718096;">
        <strong>Total classes:</strong> ${routineData.length}
    </div>`;
    
    showRoutineContainer(html);
}

function normalizeSection(section) {
    // Remove extra spaces and convert to uppercase
    return section.trim().toUpperCase().replace(/\s+/g, '_');
}

function findMatchingSection(sections, normalizedInput) {
    // Direct match
    if (sections[normalizedInput]) {
        return normalizedInput;
    }
    
    // Try to find case-insensitive match
    const sectionKeys = Object.keys(sections);
    for (const key of sectionKeys) {
        if (key.toUpperCase() === normalizedInput) {
            return key;
        }
    }
    
    // Try matching without underscores
    const cleanInput = normalizedInput.replace(/_/g, '');
    for (const key of sectionKeys) {
        if (key.replace(/_/g, '').toUpperCase() === cleanInput) {
            return key;
        }
    }
    
    return null;
}

function showRoutineContainer(html) {
    routineContainer.innerHTML = html;
}

function createNoRoutineMessage(message) {
    return `<div class="no-routine">
        <div class="icon">📅</div>
        <h3>${escapeHtml(message)}</h3>
        <p>Please check your section name and try again.</p>
    </div>`;
}

function createErrorMessage(title, message) {
    return `<div class="no-routine">
        <div class="icon">⚠️</div>
        <h3>${escapeHtml(title)}</h3>
        <p>${escapeHtml(message)}</p>
        <p style="margin-top: 10px; font-size: 0.85rem; color: #718096;">
            The routine data is generated by GitHub Actions. If this problem persists, 
            the scraper might need to be updated.
        </p>
    </div>`;
}

function showStatus(message, type) {
    statusMessage.textContent = message;
    statusMessage.className = 'status-message show ' + type;
}

function hideStatus() {
    statusMessage.className = 'status-message';
}

function setStatusIndicator(state, text) {
    statusIndicator.className = 'status-' + state;
    statusIndicator.textContent = text;
}

function escapeHtml(text) {
    if (!text) return '-';
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
}

// Refresh routine data periodically (every 5 minutes)
setInterval(() => {
    if (document.hidden) return;
    loadRoutineData();
}, 5 * 60 * 1000);
